-- Anchor — seed item bank.
--
-- Run after supabase/migrations/20260805000000_research_spec.sql. Idempotent:
-- re-running inserts nothing new, so it is safe on every deploy.
--
-- Mirrors lib/research/seed-items.ts, which is the source of truth. The row ids
-- are a deterministic hash of each item's ref slug, so seeding from either side
-- lands on the same primary key. Change an item there first, then here: the
-- grader test fails if the two drift apart.
--
-- distractors holds every option in display order for multiple choice items.
-- Which option is right lives in answer_key.index, and answer_key is not in the
-- items_public view, so the key never reaches a client.
--
-- Every answer_key here is verified: lib/research/__tests__/grader.test.ts
-- grades each item's own canonical answer and asserts 'correct'. A wrong key
-- would poison grading, hint grounding and feedback at the same time (A4, I3).
--
-- 80 items across maths, physics, chemistry, biology and English,
-- year groups 9 to 13, all four item kinds, difficulty 1 to 10.
--
-- Transfer items carry variant_of, pointing at the item whose strategy they
-- reuse in a new context (N6). Parents are listed before their variants so the
-- self-reference resolves inside this single statement.

insert into items (
  id, kind, subject, topic, skill, year_group, difficulty, stem, answer_key, rubric, worked_solution, distractors, common_misconceptions, source, verified, variant_of
) values
  -- maths / linear-equations / Y9 / difficulty 2
  ('4c11878e-58a4-4874-8e90-9060aa455b7e',
   'retrieval',
   'maths',
   'algebra',
   'linear-equations',
   'Y9',
   2,
   'Solve for x: 4x + 7 = 31. Give the value of x.',
   '{"type":"numeric","value":6}'::jsonb,
   null,
   'Subtract 7 from both sides to get 4x = 24. Divide both sides by 4, so x = 6.',
   null,
   '{"inverse_order":"Answering 9.5 adds 7 instead of subtracting it before dividing by 4."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / percentage-change / Y9 / difficulty 3
  ('da783f58-d42c-4a2a-81f2-d5fe67965ce8',
   'reasoning',
   'maths',
   'percentages',
   'percentage-change',
   'Y9',
   3,
   'A jacket costs 80 pounds. The price rises by 15%, then falls by 15% in a sale. Give the final price in pounds.',
   '{"type":"numeric","value":78.2,"tolerance":0.005}'::jsonb,
   null,
   'A 15% rise gives 80 x 1.15 = 92. A 15% fall from 92 gives 92 x 0.85 = 78.20. The fall is taken from the larger amount, so the price does not return to 80.',
   null,
   '{"percent_cancel":"Answering 80 assumes a 15% rise and a 15% fall cancel out.","rise_only":"Answering 92 stops after the rise and never applies the sale."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / indices-laws / Y9 / difficulty 3
  ('3fadf82b-b1c9-4499-8537-47f5ee41245b',
   'retrieval',
   'maths',
   'indices',
   'indices-laws',
   'Y9',
   3,
   'Simplify (3x^2)(4x^5). Write your answer in the form ax^n.',
   '{"type":"expression","canonical":"12x^7"}'::jsonb,
   null,
   'Multiply the numbers: 3 x 4 = 12. Add the indices: 2 + 5 = 7. The answer is 12x^7.',
   null,
   '{"indices_multiplied":"Answering 12x^10 multiplies the indices instead of adding them."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / order-of-operations / Y9 / difficulty 2
  ('651342ec-f857-40e2-8d1d-92f6f78e715c',
   'practice',
   'maths',
   'arithmetic',
   'order-of-operations',
   'Y9',
   2,
   'Work out 7 + 3 x 4 - 2.',
   '{"type":"numeric","value":17}'::jsonb,
   null,
   'Multiplication comes first: 3 x 4 = 12. Then 7 + 12 - 2 = 17.',
   null,
   '{"left_to_right":"Answering 38 works strictly left to right; multiplication comes first."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / quadratic-factorising / Y10 / difficulty 4
  ('0ad73cfd-5566-4403-8ff6-cfefd0298bcd',
   'reasoning',
   'maths',
   'quadratics',
   'quadratic-factorising',
   'Y10',
   4,
   'Solve x^2 - 7x + 12 = 0. Give both roots, separated by a comma.',
   '{"type":"set","values":["3","4"]}'::jsonb,
   null,
   'Two numbers multiply to 12 and add to -7: -3 and -4. So (x - 3)(x - 4) = 0, and setting each bracket to zero gives x = 3 and x = 4.',
   null,
   '{"bracket_signs_copied":"Answering -3, -4 copies the signs inside the brackets instead of solving each bracket equal to zero."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / simultaneous-equations / Y10 / difficulty 5
  ('ad021674-4424-4966-8989-f0c216f5fbe4',
   'reasoning',
   'maths',
   'simultaneous equations',
   'simultaneous-equations',
   'Y10',
   5,
   'Solve the simultaneous equations 2x + 3y = 12 and x - y = 1. Give your answer as x, y.',
   '{"type":"set","values":["3","2"],"ordered":true}'::jsonb,
   null,
   'Rearrange the second equation to x = y + 1. Substitute into the first: 2(y + 1) + 3y = 12, so 5y + 2 = 12 and y = 2. Then x = 3. Check: 2(3) + 3(2) = 12.',
   null,
   '{"values_swapped":"Answering 2, 3 puts the values the wrong way round; the first number is x."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / simultaneous-equations / Y10 / difficulty 6
  ('f922b688-65b4-443a-861a-61568809d6d8',
   'transfer',
   'maths',
   'simultaneous equations',
   'simultaneous-equations',
   'Y10',
   6,
   'Two coffees and three teas cost 12 pounds in total. One coffee costs 1 pound more than one tea. Give the price of one coffee in pounds.',
   '{"type":"numeric","value":3}'::jsonb,
   null,
   'Let c and t be the prices. Then 2c + 3t = 12 and c - t = 1. Substituting c = t + 1 gives 5t + 2 = 12, so t = 2 and c = 3. Check: 2(3) + 3(2) = 12.',
   null,
   '{"wrong_unknown":"Answering 2 gives the price of a tea, not the coffee the question asked for."}'::jsonb,
   'authored',
   true,
   'ad021674-4424-4966-8989-f0c216f5fbe4'),

  -- maths / probability-tree / Y10 / difficulty 5
  ('c96a6f67-e205-4a4d-87b2-a921956768b7',
   'practice',
   'maths',
   'probability',
   'probability-tree',
   'Y10',
   5,
   'A bag holds 4 red counters and 6 blue counters. Two are taken without replacement. Give the probability that both are red, as a fraction in its simplest form.',
   '{"type":"exact","value":"2/15","alternates":["2 / 15"]}'::jsonb,
   null,
   'The first counter is red with probability 4/10. One red counter and one counter overall are then gone, so the second is red with probability 3/9. Multiplying gives 12/90, which simplifies to 2/15.',
   null,
   '{"replacement_assumed":"Answering 4/25 treats the first counter as replaced; after one red there are 3 red among 9 counters."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / surds / Y11 / difficulty 5
  ('334565b0-ba34-45ca-8bb6-67ee31b34860',
   'reasoning',
   'maths',
   'surds',
   'surds',
   'Y11',
   5,
   'Simplify √50 + √18. Write your answer in the form a√2.',
   '{"type":"expression","canonical":"8√2"}'::jsonb,
   null,
   '√50 = √25 x √2 = 5√2 and √18 = √9 x √2 = 3√2. Adding the like terms gives 8√2.',
   null,
   '{"roots_added":"Answering √68 adds the numbers under the roots; √a + √b is not √(a + b)."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / standard-form / Y11 / difficulty 3
  ('e85ec32d-46ba-4443-81df-1f272adea41d',
   'retrieval',
   'maths',
   'standard form',
   'standard-form',
   'Y11',
   3,
   'Write 0.00042 in standard form, in the form a x 10^n.',
   '{"type":"expression","canonical":"4.2×10^-4"}'::jsonb,
   null,
   'Move the decimal point four places to the right to reach 4.2. Because the number is smaller than 1, the power is negative: 4.2 x 10^-4.',
   null,
   '{"positive_power":"Answering 4.2 x 10^4 uses a positive power; a number below 1 needs a negative power."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / pythagoras / Y11 / difficulty 5
  ('22a262f3-f2e5-4a6d-8553-7c71cfc51ca3',
   'reasoning',
   'maths',
   'pythagoras',
   'pythagoras',
   'Y11',
   5,
   'A right-angled triangle has a hypotenuse of 13 cm and one shorter side of 5 cm. Give the length of the third side in cm.',
   '{"type":"numeric","value":12}'::jsonb,
   null,
   'The hypotenuse is the longest side, so subtract: 13^2 - 5^2 = 169 - 25 = 144. The third side is √144 = 12 cm.',
   null,
   '{"squares_added":"Answering 13.9 adds the squares, which would make the given hypotenuse a shorter side."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / pythagoras / Y11 / difficulty 6
  ('db794f71-82f4-468b-8c92-58dfa7fe63c1',
   'transfer',
   'maths',
   'pythagoras',
   'pythagoras',
   'Y11',
   6,
   'A ladder 13 m long leans against a vertical wall with its foot 5 m from the base of the wall. Give the height it reaches up the wall in metres.',
   '{"type":"numeric","value":12}'::jsonb,
   null,
   'The wall, the ground and the ladder form a right-angled triangle with the ladder as the hypotenuse. The height is √(13^2 - 5^2) = √144 = 12 m.',
   null,
   '{"hypotenuse_misread":"Answering 13.9 treats the ladder as a shorter side; the ladder is the hypotenuse."}'::jsonb,
   'authored',
   true,
   '22a262f3-f2e5-4a6d-8553-7c71cfc51ca3'),

  -- maths / circle-theorems / Y11 / difficulty 4
  ('60dc0870-d1de-43be-8447-009a111cec20',
   'retrieval',
   'maths',
   'circle theorems',
   'circle-theorems',
   'Y11',
   4,
   'A triangle is drawn inside a circle with one side as the diameter. Give the size in degrees of the angle opposite that side.',
   '{"type":"numeric","value":90}'::jsonb,
   null,
   'The angle in a semicircle is a right angle, so the angle opposite the diameter is 90 degrees.',
   null,
   '{"straight_line_used":"Answering 180 uses the straight line through the centre rather than the angle in the semicircle."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / differentiation-power-rule / Y12 / difficulty 5
  ('e0264b03-22fe-4a61-8345-a20d505f3ed3',
   'reasoning',
   'maths',
   'differentiation',
   'differentiation-power-rule',
   'Y12',
   5,
   'Differentiate y = 3x^4 - 2x^2 + 7 with respect to x. Give dy/dx.',
   '{"type":"expression","canonical":"12x^3-4x"}'::jsonb,
   null,
   'Multiply by the index and drop the index by one: 3x^4 gives 12x^3 and -2x^2 gives -4x. The derivative of the constant 7 is zero, so dy/dx = 12x^3 - 4x.',
   null,
   '{"constant_kept":"Answering 12x^3 - 4x + 7 keeps the constant; the derivative of a constant is zero."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / logarithms / Y12 / difficulty 4
  ('3904a4fc-50fc-44fe-8b2f-854aaeda862c',
   'retrieval',
   'maths',
   'logarithms',
   'logarithms',
   'Y12',
   4,
   'Evaluate log to base 2 of 32.',
   '{"type":"numeric","value":5}'::jsonb,
   null,
   'Ask which power of 2 gives 32. Since 2^5 = 32, the logarithm is 5.',
   null,
   '{"halved":"Answering 16 halves 32 rather than asking which power of 2 gives 32."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / binomial-expansion / Y12 / difficulty 6
  ('cf137a68-d264-410e-8772-b7da930a7738',
   'reasoning',
   'maths',
   'binomial expansion',
   'binomial-expansion',
   'Y12',
   6,
   'In the expansion of (1 + 2x)^5, give the coefficient of x^2.',
   '{"type":"numeric","value":40}'::jsonb,
   null,
   'The x^2 term is C(5,2) x 1^3 x (2x)^2 = 10 x 4x^2 = 40x^2, so the coefficient is 40.',
   null,
   '{"coefficient_only":"Answering 10 uses the binomial coefficient alone and leaves the 2 in 2x unsquared."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / sequences-arithmetic / Y12 / difficulty 4
  ('ef7e20bd-8434-426f-8319-a4d30956636d',
   'practice',
   'maths',
   'sequences',
   'sequences-arithmetic',
   'Y12',
   4,
   'An arithmetic sequence starts 5, 9, 13 and continues in the same way. Give the 20th term.',
   '{"type":"numeric","value":81}'::jsonb,
   null,
   'The first term is 5 and the common difference is 4. There are 19 steps after the first term, so the 20th term is 5 + 19 x 4 = 81.',
   null,
   '{"extra_step":"Answering 85 uses 20 steps; the 20th term sits 19 steps after the first."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / integration-definite / Y13 / difficulty 7
  ('8c48f738-2b7a-4a72-8dde-19b67112ba08',
   'reasoning',
   'maths',
   'integration',
   'integration-definite',
   'Y13',
   7,
   'Evaluate the definite integral of 3x^2 with respect to x, from x = 1 to x = 4.',
   '{"type":"numeric","value":63}'::jsonb,
   null,
   'Integrating 3x^2 gives x^3. Substituting the limits gives 4^3 - 1^3 = 64 - 1 = 63.',
   null,
   '{"lower_limit_dropped":"Answering 64 substitutes only the upper limit; subtract the value at the lower limit."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / integration-definite / Y13 / difficulty 8
  ('98d9d24b-bbf9-4c09-8a40-1a4d1064737b',
   'transfer',
   'maths',
   'kinematics with calculus',
   'integration-definite',
   'Y13',
   8,
   'A particle moves in a straight line with velocity v = 3t^2 metres per second. Give the distance travelled in metres between t = 1 and t = 4 seconds.',
   '{"type":"numeric","value":63}'::jsonb,
   null,
   'Distance is the integral of velocity. Integrating 3t^2 gives t^3, so the distance is 4^3 - 1^3 = 63 metres.',
   null,
   '{"velocity_read_off":"Answering 48 substitutes t = 4 into the velocity instead of integrating it."}'::jsonb,
   'authored',
   true,
   '8c48f738-2b7a-4a72-8dde-19b67112ba08'),

  -- maths / vectors / Y13 / difficulty 6
  ('55f87089-fdef-45db-8200-40d7203463f9',
   'reasoning',
   'maths',
   'vectors',
   'vectors',
   'Y13',
   6,
   'Vectors a = (3, 4) and b = (-1, 2). Give the magnitude of a + b to 2 decimal places.',
   '{"type":"numeric","value":6.32,"tolerance":0.005}'::jsonb,
   null,
   'Add the components: a + b = (2, 6). The magnitude is √(2^2 + 6^2) = √40 = 6.32 to 2 decimal places.',
   null,
   '{"components_added":"Answering 8 adds the components of the resultant instead of using Pythagoras on them."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / integration-by-parts / Y13 / difficulty 9
  ('20ef59d2-ecb0-435c-84bb-d8a85a06f6e2',
   'reasoning',
   'maths',
   'integration',
   'integration-by-parts',
   'Y13',
   9,
   'Evaluate the integral of x e^x with respect to x, from x = 0 to x = 1.',
   '{"type":"numeric","value":1,"tolerance":0.005}'::jsonb,
   null,
   'Integrate by parts with u = x and dv = e^x dx, which gives x e^x - e^x. At x = 1 that is e - e = 0, and at x = 0 it is 0 - 1 = -1. The definite integral is 0 - (-1) = 1.',
   null,
   '{"product_of_integrals":"Answering 2.72, the value of e, integrates the two factors separately; the integral of a product is not the product of the integrals."}'::jsonb,
   'authored',
   true,
   null),

  -- maths / logarithms / Y13 / difficulty 9
  ('204e9822-c177-4bcc-8592-f9d02a194f92',
   'reasoning',
   'maths',
   'logarithms',
   'logarithms',
   'Y13',
   9,
   'Solve log to base 3 of x, plus log to base 3 of (x - 2), equals 1. Give the valid value of x.',
   '{"type":"numeric","value":3}'::jsonb,
   null,
   'Combine the logarithms: log base 3 of x(x - 2) = 1, so x(x - 2) = 3. That gives x^2 - 2x - 3 = 0, which factorises to (x - 3)(x + 1) = 0. Only x = 3 is valid, because x = -1 would take the logarithm of a negative number.',
   null,
   '{"invalid_root_kept":"Answering -1 keeps the root that makes the logarithm undefined."}'::jsonb,
   'authored',
   true,
   null),

  -- physics / density / Y9 / difficulty 2
  ('499e10b1-cd80-469f-843a-a4b39fc6a281',
   'retrieval',
   'physics',
   'density',
   'density',
   'Y9',
   2,
   'A block has a mass of 240 g and a volume of 30 cm^3. Give its density in g per cm^3.',
   '{"type":"numeric","value":8,"unit":"g/cm^3"}'::jsonb,
   null,
   'Density is mass divided by volume: 240 divided by 30 is 8 g per cm^3.',
   null,
   '{"formula_inverted":"Answering 0.125 divides volume by mass instead of mass by volume."}'::jsonb,
   'authored',
   true,
   null),

  -- physics / speed-distance-time / Y9 / difficulty 3
  ('9110f86a-a658-44cc-86ce-22b803da749a',
   'reasoning',
   'physics',
   'motion',
   'speed-distance-time',
   'Y9',
   3,
   'A runner covers 1500 m in 300 s. Give the average speed in m/s.',
   '{"type":"numeric","value":5,"unit":"m/s"}'::jsonb,
   null,
   'Speed is distance divided by time: 1500 divided by 300 is 5 m/s.',
   null,
   '{"time_over_distance":"Answering 0.2 divides time by distance."}'::jsonb,
   'authored',
   true,
   null),

  -- physics / ohms-law / Y10 / difficulty 3
  ('8ffb1251-384c-428f-8128-a923142b5761',
   'retrieval',
   'physics',
   'electricity',
   'ohms-law',
   'Y10',
   3,
   'A resistor carries a current of 0.5 A when 12 V is across it. Give its resistance in ohms.',
   '{"type":"numeric","value":24,"unit":"ohms"}'::jsonb,
   null,
   'Rearranging V = IR gives R = V divided by I, so R = 12 divided by 0.5 = 24 ohms.',
   null,
   '{"power_formula_used":"Answering 6 multiplies voltage by current, which gives power rather than resistance."}'::jsonb,
   'authored',
   true,
   null),

  -- physics / newton-second-law / Y10 / difficulty 4
  ('26d9655b-7094-4af9-8018-9085e0b993ab',
   'reasoning',
   'physics',
   'forces',
   'newton-second-law',
   'Y10',
   4,
   'A car of mass 1200 kg accelerates at 2.5 m/s^2. Give the resultant force in newtons.',
   '{"type":"numeric","value":3000,"unit":"N"}'::jsonb,
   null,
   'Force is mass times acceleration: 1200 x 2.5 = 3000 N.',
   null,
   '{"divided_instead":"Answering 480 divides mass by acceleration instead of multiplying."}'::jsonb,
   'authored',
   true,
   null),

  -- physics / series-parallel-resistance / Y10 / difficulty 5
  ('968988e2-7f62-4e38-85b9-c1f42ceede12',
   'reasoning',
   'physics',
   'electricity',
   'series-parallel-resistance',
   'Y10',
   5,
   'A 6 ohm resistor and a 3 ohm resistor are connected in parallel. Give the total resistance in ohms.',
   '{"type":"numeric","value":2,"unit":"ohms"}'::jsonb,
   null,
   'For resistors in parallel, 1/R = 1/6 + 1/3 = 1/2, so R = 2 ohms. The total is always smaller than the smallest single resistor.',
   null,
   '{"series_rule_used":"Answering 9 adds the resistances, which is the rule for series, not parallel."}'::jsonb,
   'authored',
   true,
   null),

  -- physics / series-parallel-resistance / Y10 / difficulty 6
  ('11c24cd0-266d-4ffe-8635-cbba32c05900',
   'transfer',
   'physics',
   'electricity',
   'series-parallel-resistance',
   'Y10',
   6,
   'A 6 ohm heater and a 3 ohm lamp are connected side by side across a 12 V supply. Give the total current drawn from the supply in amps.',
   '{"type":"numeric","value":6,"unit":"A"}'::jsonb,
   null,
   'Each branch has the full 12 V across it. The heater draws 12 divided by 6 = 2 A and the lamp draws 12 divided by 3 = 4 A, so the supply provides 6 A.',
   null,
   '{"one_branch_only":"Answering 2 uses the heater branch alone; the supply current is the sum of the branch currents."}'::jsonb,
   'authored',
   true,
   '968988e2-7f62-4e38-85b9-c1f42ceede12'),

  -- physics / kinematics-suvat / Y11 / difficulty 6
  ('8eb4ef75-ddf2-4a97-8491-e9b3959bca45',
   'reasoning',
   'physics',
   'motion',
   'kinematics-suvat',
   'Y11',
   6,
   'A ball is dropped from rest and falls for 3.0 s. Taking g = 9.8 m/s^2 and ignoring air resistance, give the distance fallen in metres.',
   '{"type":"numeric","value":44.1,"tolerance":0.05,"unit":"m"}'::jsonb,
   null,
   'Use s = ut + half a t^2 with u = 0. That gives s = 0.5 x 9.8 x 3.0^2 = 44.1 m.',
   null,
   '{"speed_given_as_distance":"Answering 29.4 gives the speed after 3 s, not the distance fallen."}'::jsonb,
   'authored',
   true,
   null),

  -- physics / waves-equation / Y11 / difficulty 4
  ('c1fd33cf-3e53-4ebd-83b2-4629c4e6d19f',
   'retrieval',
   'physics',
   'waves',
   'waves-equation',
   'Y11',
   4,
   'A wave has a frequency of 50 Hz and a wavelength of 6 m. Give its speed in m/s.',
   '{"type":"numeric","value":300,"unit":"m/s"}'::jsonb,
   null,
   'Wave speed is frequency times wavelength: 50 x 6 = 300 m/s.',
   null,
   '{"divided_instead":"Answering 0.12 divides wavelength by frequency instead of multiplying."}'::jsonb,
   'authored',
   true,
   null),

  -- physics / energy-conservation / Y11 / difficulty 6
  ('60bf2c63-db0e-4b1d-89b5-4a9921a0dc53',
   'reasoning',
   'physics',
   'energy',
   'energy-conservation',
   'Y11',
   6,
   'A 0.5 kg ball is dropped from a height of 20 m. Taking g = 10 N/kg and ignoring air resistance, give its speed just before it lands, in m/s.',
   '{"type":"numeric","value":20,"unit":"m/s"}'::jsonb,
   null,
   'The gravitational store mgh becomes the kinetic store half m v^2, so v = √(2gh) = √(2 x 10 x 20) = 20 m/s. The mass cancels.',
   null,
   '{"energy_given_as_speed":"Answering 100 gives the energy in joules rather than the speed."}'::jsonb,
   'authored',
   true,
   null),

  -- physics / moments / Y11 / difficulty 5
  ('d1ad85d4-083e-4e6e-8e2c-26f2177c83c4',
   'practice',
   'physics',
   'moments',
   'moments',
   'Y11',
   5,
   'A uniform plank balances on a pivot at its centre. A 30 N weight sits 0.8 m from the pivot on the left. Give the distance from the pivot, in metres, at which a 40 N weight balances it on the right.',
   '{"type":"numeric","value":0.6,"tolerance":0.005,"unit":"m"}'::jsonb,
   null,
   'Balance the moments. The left moment is 30 x 0.8 = 24 N m, so 40 x d = 24 and d = 0.6 m.',
   null,
   '{"distances_matched":"Answering 0.8 matches the distances; it is the moments, force times distance, that must match."}'::jsonb,
   'authored',
   true,
   null),

  -- physics / momentum / Y12 / difficulty 6
  ('bca8b84d-588c-4e87-8b95-0023de3971dd',
   'reasoning',
   'physics',
   'momentum',
   'momentum',
   'Y12',
   6,
   'A 2 kg trolley moving at 3 m/s collides with a stationary 1 kg trolley and the two move off together. Give their common velocity in m/s.',
   '{"type":"numeric","value":2,"unit":"m/s"}'::jsonb,
   null,
   'Momentum before the collision is 2 x 3 = 6 kg m/s. Afterwards the combined mass is 3 kg, so v = 6 divided by 3 = 2 m/s.',
   null,
   '{"speeds_averaged":"Answering 1.5 averages the two speeds; it is momentum that is conserved."}'::jsonb,
   'authored',
   true,
   null),

  -- physics / power-electrical / Y12 / difficulty 4
  ('f8ea7a88-eb6b-4162-88b9-07ae203f5fd8',
   'retrieval',
   'physics',
   'electricity',
   'power-electrical',
   'Y12',
   4,
   'A kettle runs from 230 V and draws 9.0 A. Give its power in watts.',
   '{"type":"numeric","value":2070,"unit":"W"}'::jsonb,
   null,
   'Electrical power is voltage times current: 230 x 9.0 = 2070 W.',
   null,
   '{"divided_instead":"Answering 25.6 divides voltage by current, which gives resistance."}'::jsonb,
   'authored',
   true,
   null),

  -- physics / specific-heat / Y12 / difficulty 7
  ('5b5562d0-8e4b-4cbe-885c-948a874a3be0',
   'reasoning',
   'physics',
   'thermal physics',
   'specific-heat',
   'Y12',
   7,
   'Give the energy in joules needed to raise the temperature of 2.0 kg of water by 15 degrees Celsius. Use a specific heat capacity of 4200 J per kg per degree.',
   '{"type":"numeric","value":126000,"unit":"J"}'::jsonb,
   null,
   'Energy is mass x specific heat capacity x temperature change: 2.0 x 4200 x 15 = 126000 J.',
   null,
   '{"mass_omitted":"Answering 63000 leaves the mass out of the calculation."}'::jsonb,
   'authored',
   true,
   null),

  -- physics / circular-motion / Y13 / difficulty 8
  ('2e8d375b-e761-4165-89ea-2229cd9c160b',
   'reasoning',
   'physics',
   'circular motion',
   'circular-motion',
   'Y13',
   8,
   'An object of mass 0.20 kg moves in a circle of radius 0.50 m at 4.0 m/s. Give the centripetal force in newtons.',
   '{"type":"numeric","value":6.4,"tolerance":0.05,"unit":"N"}'::jsonb,
   null,
   'F = m v^2 divided by r, so F = 0.20 x 4.0^2 divided by 0.50 = 0.20 x 16 divided by 0.50 = 6.4 N.',
   null,
   '{"speed_not_squared":"Answering 1.6 uses v rather than v squared."}'::jsonb,
   'authored',
   true,
   null),

  -- physics / energy-conservation / Y13 / difficulty 8
  ('317ccb01-579a-4db7-86f6-2273587f24b1',
   'transfer',
   'physics',
   'energy',
   'energy-conservation',
   'Y13',
   8,
   'A pendulum bob is released from rest 0.45 m above its lowest point. Taking g = 10 N/kg and ignoring resistance, give its speed at the lowest point in m/s.',
   '{"type":"numeric","value":3,"unit":"m/s"}'::jsonb,
   null,
   'All of the gravitational store becomes kinetic, so v = √(2gh) = √(2 x 10 x 0.45) = √9 = 3 m/s.',
   null,
   '{"height_restated":"Answering 0.45 repeats the height; convert the energy store first."}'::jsonb,
   'authored',
   true,
   '60bf2c63-db0e-4b1d-89b5-4a9921a0dc53'),

  -- physics / photoelectric-effect / Y13 / difficulty 9
  ('15dfa3fa-b0aa-42f4-87e4-dba0d7681e2a',
   'reasoning',
   'physics',
   'quantum physics',
   'photoelectric-effect',
   'Y13',
   9,
   'A metal has a work function of 2.0 eV. Light with photon energy 5.0 eV falls on it. Give the maximum kinetic energy of an emitted electron in eV.',
   '{"type":"numeric","value":3,"tolerance":0.05,"unit":"eV"}'::jsonb,
   null,
   'The photon energy pays for the escape first: maximum kinetic energy = 5.0 - 2.0 = 3.0 eV.',
   null,
   '{"energies_added":"Answering 7 adds the work function; the work function is spent escaping the surface, so subtract it."}'::jsonb,
   'authored',
   true,
   null),

  -- physics / momentum / Y13 / difficulty 10
  ('24c0dcc6-8967-44f0-826f-dff420da5296',
   'reasoning',
   'physics',
   'momentum',
   'momentum',
   'Y13',
   10,
   'A 0.150 kg ball travelling at 8.0 m/s hits a wall and rebounds at 6.0 m/s in the opposite direction. The contact lasts 0.020 s. Give the size of the average force on the ball in newtons.',
   '{"type":"numeric","value":105,"tolerance":0.5,"unit":"N"}'::jsonb,
   null,
   'The velocity changes from +8.0 to -6.0 m/s, a change of 14.0 m/s. The change in momentum is 0.150 x 14.0 = 2.1 kg m/s, and dividing by the contact time gives 2.1 divided by 0.020 = 105 N.',
   null,
   '{"direction_ignored":"Answering 15 uses the difference in speeds, 8.0 minus 6.0, and misses that the ball reverses direction."}'::jsonb,
   'authored',
   true,
   null),

  -- chemistry / atomic-structure / Y9 / difficulty 2
  ('c7190431-1017-457b-8459-54effe7b7521',
   'retrieval',
   'chemistry',
   'atomic structure',
   'atomic-structure',
   'Y9',
   2,
   'An atom of sodium has atomic number 11 and mass number 23. Give the number of neutrons.',
   '{"type":"numeric","value":12}'::jsonb,
   null,
   'Neutrons are the mass number minus the number of protons: 23 - 11 = 12.',
   null,
   '{"mass_number_used":"Answering 23 gives the mass number, which counts protons and neutrons together."}'::jsonb,
   'authored',
   true,
   null),

  -- chemistry / balancing-equations / Y9 / difficulty 3
  ('852d786c-55d9-4fca-805c-6636fe396f3c',
   'retrieval',
   'chemistry',
   'chemical equations',
   'balancing-equations',
   'Y9',
   3,
   'Balance this equation by giving the three missing numbers in order, separated by commas: __ H2 + __ O2 gives __ H2O.',
   '{"type":"set","values":["2","1","2"],"ordered":true}'::jsonb,
   null,
   'Two molecules of hydrogen and one of oxygen make two of water: 2H2 + O2 gives 2H2O. That is 4 hydrogen atoms and 2 oxygen atoms on each side.',
   null,
   '{"wrong_side_adjusted":"Answering 1, 2, 1 doubles the oxygen on the left instead of doubling the water on the right, which leaves oxygen unbalanced."}'::jsonb,
   'authored',
   true,
   null),

  -- chemistry / separation-techniques / Y9 / difficulty 3
  ('5e674949-a3b6-47c7-8491-4acbc1eef1f9',
   'practice',
   'chemistry',
   'separation techniques',
   'separation-techniques',
   'Y9',
   3,
   'Which method separates a dissolved solid from its solution?',
   '{"type":"choice","index":1}'::jsonb,
   null,
   'A dissolved solid passes straight through filter paper. Evaporating the solvent leaves the solid behind as crystals, so crystallisation is the method.',
   '["Filtration","Crystallisation","Chromatography","Decanting"]'::jsonb,
   '{"filtration_assumed":"Choosing filtration assumes the solid is undissolved; a dissolved solid passes through the paper."}'::jsonb,
   'authored',
   true,
   null),

  -- chemistry / mole-calculations / Y10 / difficulty 5
  ('81cae103-0dd7-463d-8679-8d491946a5f3',
   'reasoning',
   'chemistry',
   'moles',
   'mole-calculations',
   'Y10',
   5,
   'Give the number of moles in 8.0 g of magnesium oxide, MgO. Use Mr = 40.',
   '{"type":"numeric","value":0.2,"tolerance":0.005,"unit":"mol"}'::jsonb,
   null,
   'Moles are mass divided by Mr: 8.0 divided by 40 is 0.2 mol.',
   null,
   '{"multiplied_instead":"Answering 320 multiplies mass by Mr instead of dividing."}'::jsonb,
   'authored',
   true,
   null),

  -- chemistry / mole-calculations / Y10 / difficulty 7
  ('b3102ca1-cf4d-4a7b-8571-954703a4e871',
   'transfer',
   'chemistry',
   'moles',
   'mole-calculations',
   'Y10',
   7,
   'A tablet contains 0.50 g of calcium carbonate, CaCO3, with Mr = 100. Give the number of moles of calcium carbonate in the tablet.',
   '{"type":"numeric","value":0.005,"tolerance":0.00005,"unit":"mol"}'::jsonb,
   null,
   'Moles are mass divided by Mr: 0.50 divided by 100 is 0.005 mol.',
   null,
   '{"decimal_slipped":"Answering 0.05 slips one decimal place; 0.50 divided by 100 is 0.005."}'::jsonb,
   'authored',
   true,
   '81cae103-0dd7-463d-8679-8d491946a5f3'),

  -- chemistry / percentage-yield / Y10 / difficulty 5
  ('bc96707d-ce98-41d3-8bbb-ee570c21b46d',
   'reasoning',
   'chemistry',
   'yield',
   'percentage-yield',
   'Y10',
   5,
   'A reaction has a theoretical yield of 25.0 g and produces 18.0 g of product. Give the percentage yield.',
   '{"type":"numeric","value":72,"tolerance":0.05}'::jsonb,
   null,
   'Percentage yield is actual divided by theoretical, times 100: 18.0 divided by 25.0 x 100 = 72.',
   null,
   '{"fraction_inverted":"Answering 139 divides theoretical by actual; the actual mass goes on top."}'::jsonb,
   'authored',
   true,
   null),

  -- chemistry / ionic-bonding / Y10 / difficulty 4
  ('375062c6-f64f-4650-86c8-d8cc9e763296',
   'retrieval',
   'chemistry',
   'bonding',
   'ionic-bonding',
   'Y10',
   4,
   'Give the formula of the ionic compound formed between magnesium and chlorine.',
   '{"type":"exact","value":"MgCl2"}'::jsonb,
   null,
   'Magnesium forms a 2+ ion and chlorine forms a 1- ion. Two chloride ions balance one magnesium ion, giving MgCl2.',
   null,
   '{"charges_unbalanced":"Answering MgCl leaves the charges unbalanced; the 2+ on magnesium needs two chloride ions."}'::jsonb,
   'authored',
   true,
   null),

  -- chemistry / empirical-formula / Y11 / difficulty 6
  ('6b230154-20a7-46ea-838a-ca1e50a87464',
   'reasoning',
   'chemistry',
   'formulae',
   'empirical-formula',
   'Y11',
   6,
   'A compound contains 2.4 g of carbon and 0.6 g of hydrogen. Using Ar values of 12 for carbon and 1 for hydrogen, give its empirical formula.',
   '{"type":"exact","value":"CH3"}'::jsonb,
   null,
   'Divide each mass by its Ar: carbon gives 2.4 divided by 12 = 0.2 mol and hydrogen gives 0.6 divided by 1 = 0.6 mol. Dividing both by the smaller gives a ratio of 1 to 3, so the empirical formula is CH3.',
   null,
   '{"mass_ratio_used":"Answering C4H uses the ratio of masses; divide each mass by its Ar first."}'::jsonb,
   'authored',
   true,
   null),

  -- chemistry / titration-calculation / Y11 / difficulty 7
  ('90869e95-ab5c-413b-8006-516fdf3a2ca5',
   'reasoning',
   'chemistry',
   'titration',
   'titration-calculation',
   'Y11',
   7,
   '25.0 cm^3 of 0.100 mol/dm^3 sodium hydroxide is neutralised by 20.0 cm^3 of hydrochloric acid. The reaction is 1 to 1. Give the concentration of the acid in mol/dm^3.',
   '{"type":"numeric","value":0.125,"tolerance":0.0005,"unit":"mol/dm^3"}'::jsonb,
   null,
   'Moles of sodium hydroxide are 0.0250 x 0.100 = 0.00250 mol. The ratio is 1 to 1, so the acid supplies 0.00250 mol as well. Its concentration is 0.00250 divided by 0.0200 = 0.125 mol/dm^3.',
   null,
   '{"volumes_swapped":"Answering 0.08 divides by the wrong volume; the acid''s moles go over the acid''s volume."}'::jsonb,
   'authored',
   true,
   null),

  -- chemistry / rates-collision-theory / Y11 / difficulty 6
  ('af84b02a-549e-4670-837d-218c036bde5a',
   'reasoning',
   'chemistry',
   'rates of reaction',
   'rates-collision-theory',
   'Y11',
   6,
   'Explain why raising the temperature increases the rate of a chemical reaction. Write two or three sentences.',
   '{"type":"rubric","passMark":0.6,"criteria":[{"id":"collision_frequency","weight":1,"keywords":["collide more often","more collisions","collision frequency","collide more frequently","more frequent collisions"]},{"id":"particle_speed","weight":1,"keywords":["move faster","moving faster","more kinetic energy","greater kinetic energy","particles speed up"]},{"id":"activation_energy","weight":1,"keywords":["activation energy","enough energy to react","sufficient energy"]}]}'::jsonb,
   '{"criteria":[{"id":"collision_frequency","weight":1,"keywords":["collide more often","more collisions","collision frequency","collide more frequently","more frequent collisions"]},{"id":"particle_speed","weight":1,"keywords":["move faster","moving faster","more kinetic energy","greater kinetic energy","particles speed up"]},{"id":"activation_energy","weight":1,"keywords":["activation energy","enough energy to react","sufficient energy"]}],"passMark":0.6}'::jsonb,
   'At a higher temperature the particles have more kinetic energy, so they move faster and collide more often. More importantly, a greater proportion of those collisions have at least the activation energy, so more of them are successful.',
   null,
   '{"collisions_only":"Saying only that particles collide more often misses the larger effect: more collisions now reach the activation energy."}'::jsonb,
   'authored',
   true,
   null),

  -- chemistry / acid-base-ph / Y12 / difficulty 6
  ('ea8f59e9-a882-44b7-83a8-67bbd3d96279',
   'reasoning',
   'chemistry',
   'acids and bases',
   'acid-base-ph',
   'Y12',
   6,
   'Give the pH of a 0.010 mol/dm^3 solution of a strong monoprotic acid.',
   '{"type":"numeric","value":2}'::jsonb,
   null,
   'A strong monoprotic acid fully dissociates, so the hydrogen ion concentration is 0.010 mol/dm^3. pH is minus the log to base 10 of that, which is 2.',
   null,
   '{"sign_dropped":"Answering -2 leaves out the minus sign in the pH definition."}'::jsonb,
   'authored',
   true,
   null),

  -- chemistry / electrolysis / Y12 / difficulty 6
  ('5b3d4929-005e-4c03-8638-3637b37538f9',
   'reasoning',
   'chemistry',
   'electrolysis',
   'electrolysis',
   'Y12',
   6,
   'Molten lead bromide is electrolysed. Name the product formed at the cathode.',
   '{"type":"exact","value":"lead","alternates":["pb","lead metal","molten lead"]}'::jsonb,
   null,
   'Positive ions move to the cathode. Lead ions gain electrons there and form lead metal.',
   null,
   '{"electrodes_swapped":"Answering bromine names the product at the anode; positive ions move to the cathode."}'::jsonb,
   'authored',
   true,
   null),

  -- chemistry / organic-nomenclature / Y13 / difficulty 6
  ('07826596-81f2-45e0-8850-96bc66bd75c6',
   'retrieval',
   'chemistry',
   'organic chemistry',
   'organic-nomenclature',
   'Y13',
   6,
   'Give the molecular formula of butane.',
   '{"type":"exact","value":"C4H10"}'::jsonb,
   null,
   'Butane has four carbon atoms, and alkanes follow CnH2n+2, so the formula is C4H10.',
   null,
   '{"alkene_formula_used":"Answering C4H8 uses the alkene formula CnH2n; alkanes are CnH2n+2."}'::jsonb,
   'authored',
   true,
   null),

  -- chemistry / equilibrium-le-chatelier / Y13 / difficulty 8
  ('708f4317-1003-4959-8db3-0bfd02f84727',
   'reasoning',
   'chemistry',
   'equilibrium',
   'equilibrium-le-chatelier',
   'Y13',
   8,
   'Nitrogen and hydrogen react reversibly to form ammonia: N2 + 3H2 gives 2NH3, and the forward reaction is exothermic. State and explain the effect of raising the pressure on the yield of ammonia.',
   '{"type":"rubric","passMark":0.6,"criteria":[{"id":"direction","weight":1,"keywords":["yield increases","increases","shifts right","moves right","more ammonia","goes up"]},{"id":"moles","weight":1,"keywords":["fewer moles","fewer molecules","four moles","two moles","side with fewer","fewer gas molecules"]},{"id":"principle","weight":1,"keywords":["oppose","opposes","counteract","le chatelier","reduce the pressure"]}]}'::jsonb,
   '{"criteria":[{"id":"direction","weight":1,"keywords":["yield increases","increases","shifts right","moves right","more ammonia","goes up"]},{"id":"moles","weight":1,"keywords":["fewer moles","fewer molecules","four moles","two moles","side with fewer","fewer gas molecules"]},{"id":"principle","weight":1,"keywords":["oppose","opposes","counteract","le chatelier","reduce the pressure"]}],"passMark":0.6}'::jsonb,
   'There are four moles of gas on the left and two on the right. Raising the pressure shifts the position of equilibrium towards the side with fewer moles of gas, which opposes the change, so the yield of ammonia increases.',
   null,
   '{"temperature_argument":"Explaining the shift with the exothermic forward reaction answers a temperature change, not a pressure change."}'::jsonb,
   'authored',
   true,
   null),

  -- biology / cell-structure / Y9 / difficulty 1
  ('700afdf3-2469-46f9-819b-56fde5b05f03',
   'retrieval',
   'biology',
   'cell biology',
   'cell-structure',
   'Y9',
   1,
   'Name the part of an animal cell that holds the genetic material.',
   '{"type":"exact","value":"nucleus","alternates":["the nucleus"]}'::jsonb,
   null,
   'The nucleus holds the chromosomes, which carry the cell''s DNA.',
   null,
   '{"mitochondria_named":"Answering mitochondria names the site of aerobic respiration; almost all of the cell''s DNA sits in the nucleus."}'::jsonb,
   'authored',
   true,
   null),

  -- biology / photosynthesis / Y9 / difficulty 2
  ('66a79204-3b8e-4782-804c-db86344b6154',
   'retrieval',
   'biology',
   'photosynthesis',
   'photosynthesis',
   'Y9',
   2,
   'Name the gas a leaf takes in during photosynthesis.',
   '{"type":"exact","value":"carbon dioxide","alternates":["co2","carbon-dioxide"]}'::jsonb,
   null,
   'Photosynthesis uses carbon dioxide and water to make glucose, and releases oxygen.',
   null,
   '{"oxygen_named":"Answering oxygen names the gas the leaf releases, not the gas it takes in."}'::jsonb,
   'authored',
   true,
   null),

  -- biology / photosynthesis / Y9 / difficulty 4
  ('081543aa-1c61-4ac4-8f40-d5e0e47a319a',
   'reasoning',
   'biology',
   'photosynthesis',
   'photosynthesis',
   'Y9',
   4,
   'A plant is kept in darkness for 48 hours before a starch test. Explain why.',
   '{"type":"rubric","passMark":0.9,"criteria":[{"id":"removes_starch","weight":1,"keywords":["use up the starch","uses up the starch","used up the starch","uses up its starch","remove the starch","removes the starch","destarch","no starch left"]},{"id":"valid_test","weight":1,"keywords":["fair test","valid","control","made during the experiment","made during the test","comes from the experiment"]}]}'::jsonb,
   '{"criteria":[{"id":"removes_starch","weight":1,"keywords":["use up the starch","uses up the starch","used up the starch","uses up its starch","remove the starch","removes the starch","destarch","no starch left"]},{"id":"valid_test","weight":1,"keywords":["fair test","valid","control","made during the experiment","made during the test","comes from the experiment"]}],"passMark":0.9}'::jsonb,
   'Without light the plant cannot photosynthesise, so it uses up the starch it had already stored. Any starch found afterwards must have been made during the experiment, which makes the test fair.',
   null,
   '{"plant_harmed":"Saying the darkness harms the plant confuses stopping photosynthesis with damaging the plant."}'::jsonb,
   'authored',
   true,
   null),

  -- biology / microscopy-magnification / Y9 / difficulty 4
  ('e0f73baf-f223-43b1-8f08-b715066d043f',
   'practice',
   'biology',
   'microscopy',
   'microscopy-magnification',
   'Y9',
   4,
   'A cell appears 40 mm wide under a microscope at a total magnification of 200 times. Give the real width of the cell in micrometres.',
   '{"type":"numeric","value":200,"unit":"micrometres"}'::jsonb,
   null,
   'Real size is image size divided by magnification: 40 divided by 200 is 0.2 mm. There are 1000 micrometres in a millimetre, so the width is 200 micrometres.',
   null,
   '{"unit_not_converted":"Answering 0.2 stops at millimetres; the question asks for micrometres.","multiplied_instead":"Answering 8000 multiplies by the magnification instead of dividing."}'::jsonb,
   'authored',
   true,
   null),

  -- biology / enzymes / Y10 / difficulty 3
  ('6c97c454-dbd6-4b4e-853d-949a8d180244',
   'retrieval',
   'biology',
   'enzymes',
   'enzymes',
   'Y10',
   3,
   'Name the type of molecule that every enzyme is made from.',
   '{"type":"exact","value":"protein","alternates":["proteins","a protein"]}'::jsonb,
   null,
   'Enzymes are proteins. The folded shape of the protein gives each enzyme an active site that fits one substrate.',
   null,
   '{"substrate_named":"Answering carbohydrate names a substrate that many enzymes act on, not the enzyme itself."}'::jsonb,
   'authored',
   true,
   null),

  -- biology / enzymes / Y13 / difficulty 8
  ('e2bd8a9c-d062-41da-8dbd-0a2edec5652c',
   'transfer',
   'biology',
   'enzymes',
   'enzymes',
   'Y13',
   8,
   'An enzyme is heated to 80 degrees Celsius and stops working permanently. Name the change to the enzyme that explains this.',
   '{"type":"exact","value":"denaturation","alternates":["denatured","it is denatured","denaturing","denatures","the enzyme denatures"]}'::jsonb,
   null,
   'Heat breaks the bonds that hold the folded shape, so the active site changes shape permanently and the substrate no longer fits. The enzyme has been denatured.',
   null,
   '{"enzyme_killed":"Saying the enzyme is killed treats it as alive; an enzyme is a molecule that loses its shape."}'::jsonb,
   'authored',
   true,
   '6c97c454-dbd6-4b4e-853d-949a8d180244'),

  -- biology / osmosis / Y10 / difficulty 5
  ('15204e05-30a7-4b03-8e2c-9fd7c506c455',
   'reasoning',
   'biology',
   'transport in cells',
   'osmosis',
   'Y10',
   5,
   'Potato cylinders are left in a concentrated sugar solution for an hour. State what happens to their mass.',
   '{"type":"exact","value":"decreases","alternates":["decrease","decreased","it decreases","mass decreases","goes down","falls","loses mass","it loses mass"]}'::jsonb,
   null,
   'The solution outside is more concentrated than the cell contents, so water leaves the cells by osmosis and the cylinders lose mass.',
   null,
   '{"water_direction_reversed":"Answering that the mass increases has water moving into the more concentrated solution; water moves the other way."}'::jsonb,
   'authored',
   true,
   null),

  -- biology / genetics-punnett / Y10 / difficulty 5
  ('350c6a04-d73d-40a6-86ec-52b2f5fb1d74',
   'reasoning',
   'biology',
   'genetics',
   'genetics-punnett',
   'Y10',
   5,
   'Two parents are both heterozygous for a recessive condition, Bb crossed with Bb. Give the percentage of offspring expected to show the recessive phenotype.',
   '{"type":"numeric","value":25}'::jsonb,
   null,
   'The cross gives BB, Bb, Bb and bb. Only bb shows the recessive phenotype, which is one outcome in four, or 25%.',
   null,
   '{"carriers_counted":"Answering 50 counts the heterozygous offspring as showing the trait; only bb shows it."}'::jsonb,
   'authored',
   true,
   null),

  -- biology / genetics-punnett / Y11 / difficulty 6
  ('687449f8-e525-43fa-877a-00e6fac45b88',
   'transfer',
   'biology',
   'genetics',
   'genetics-punnett',
   'Y11',
   6,
   'Cystic fibrosis is caused by a recessive allele. Both parents are carriers. Out of 100 children, give the number expected to have cystic fibrosis.',
   '{"type":"numeric","value":25}'::jsonb,
   null,
   'Two carriers give a one in four chance that a child inherits both recessive alleles, so 25 of 100 children are expected to have the condition.',
   null,
   '{"carriers_as_affected":"Answering 50 counts the carriers as affected; a carrier has one working allele and does not have the condition."}'::jsonb,
   'authored',
   true,
   '350c6a04-d73d-40a6-86ec-52b2f5fb1d74'),

  -- biology / respiration / Y11 / difficulty 5
  ('6497a4b2-8ef7-4f70-8f95-e7b47d1e8982',
   'reasoning',
   'biology',
   'respiration',
   'respiration',
   'Y11',
   5,
   'During hard exercise a muscle cell runs short of oxygen. Name the substance that then builds up in the muscle.',
   '{"type":"exact","value":"lactic acid","alternates":["lactate"]}'::jsonb,
   null,
   'Without enough oxygen the muscle respires anaerobically, breaking glucose down to lactic acid.',
   null,
   '{"aerobic_product_named":"Answering carbon dioxide names the aerobic product; anaerobic respiration in muscle gives lactic acid."}'::jsonb,
   'authored',
   true,
   null),

  -- biology / cell-structure / Y11 / difficulty 3
  ('bb8204b2-dafe-4ed8-8f7f-fb544ce4b942',
   'retrieval',
   'biology',
   'cell biology',
   'cell-structure',
   'Y11',
   3,
   'Which structure is found in a plant cell but not in an animal cell?',
   '{"type":"choice","index":1}'::jsonb,
   null,
   'Plant cells have a cellulose cell wall outside the membrane. Ribosomes, mitochondria and a nucleus are found in both cell types.',
   '["Ribosome","Cell wall","Mitochondrion","Nucleus"]'::jsonb,
   '{"plants_lack_mitochondria":"Choosing mitochondrion assumes plants do not respire; plant cells respire and have mitochondria."}'::jsonb,
   'authored',
   true,
   null),

  -- biology / homeostasis-blood-glucose / Y12 / difficulty 6
  ('1f90deae-2703-4324-8020-f42829fbdbde',
   'reasoning',
   'biology',
   'homeostasis',
   'homeostasis-blood-glucose',
   'Y12',
   6,
   'Blood glucose rises after a meal. Explain how the body brings it back down.',
   '{"type":"rubric","passMark":0.6,"criteria":[{"id":"hormone","weight":1,"keywords":["insulin"]},{"id":"source","weight":1,"keywords":["pancreas"]},{"id":"effect","weight":1,"keywords":["glycogen","liver","take up glucose","takes up glucose","stored","absorb glucose"]}]}'::jsonb,
   '{"criteria":[{"id":"hormone","weight":1,"keywords":["insulin"]},{"id":"source","weight":1,"keywords":["pancreas"]},{"id":"effect","weight":1,"keywords":["glycogen","liver","take up glucose","takes up glucose","stored","absorb glucose"]}],"passMark":0.6}'::jsonb,
   'The pancreas detects the rise and releases insulin. Insulin makes liver and muscle cells take glucose out of the blood and store it as glycogen, so blood glucose falls.',
   null,
   '{"glucagon_swapped":"Naming glucagon reverses the pair; glucagon raises blood glucose and insulin lowers it."}'::jsonb,
   'authored',
   true,
   null),

  -- biology / transport-xylem / Y12 / difficulty 6
  ('fc428694-ceb5-4a96-8d3e-26ba0a1b52c4',
   'reasoning',
   'biology',
   'transport in plants',
   'transport-xylem',
   'Y12',
   6,
   'Which change increases the rate of transpiration from a leaf?',
   '{"type":"choice","index":2}'::jsonb,
   null,
   'Moving air carries water vapour away from the leaf surface, which keeps the concentration gradient steep, so transpiration speeds up.',
   '["Higher humidity","Lower temperature","Faster air movement","Less light"]'::jsonb,
   '{"humidity_reversed":"Choosing higher humidity reverses the gradient; damp air slows evaporation from the leaf."}'::jsonb,
   'authored',
   true,
   null),

  -- biology / natural-selection / Y12 / difficulty 7
  ('9b4fe0be-1c45-42fc-86ed-f0609086956e',
   'reasoning',
   'biology',
   'evolution',
   'natural-selection',
   'Y12',
   7,
   'Explain how a population of bacteria becomes resistant to an antibiotic.',
   '{"type":"rubric","passMark":0.6,"criteria":[{"id":"variation","weight":1,"keywords":["mutation","mutations","random change","variation"]},{"id":"selection","weight":1,"keywords":["survive","survives","survived","killed","are killed","selection pressure"]},{"id":"reproduction","weight":1,"keywords":["reproduce","reproduces","pass on","passed on","offspring","divide"]}]}'::jsonb,
   '{"criteria":[{"id":"variation","weight":1,"keywords":["mutation","mutations","random change","variation"]},{"id":"selection","weight":1,"keywords":["survive","survives","survived","killed","are killed","selection pressure"]},{"id":"reproduction","weight":1,"keywords":["reproduce","reproduces","pass on","passed on","offspring","divide"]}],"passMark":0.6}'::jsonb,
   'Bacteria in the population vary because of random mutation. When the antibiotic is used, the bacteria without resistance are killed and the resistant ones survive. The survivors reproduce and pass the allele on, so the resistant form becomes common.',
   null,
   '{"adaptation_on_demand":"Saying the bacteria become resistant because they need to be treats the change as deliberate; resistance appears by chance mutation and is then selected."}'::jsonb,
   'authored',
   true,
   null),

  -- biology / immune-response / Y13 / difficulty 7
  ('4e60eb29-e648-4d1b-88df-47c7d66d0059',
   'retrieval',
   'biology',
   'immunity',
   'immune-response',
   'Y13',
   7,
   'Name the type of white blood cell that produces antibodies.',
   '{"type":"exact","value":"lymphocyte","alternates":["lymphocytes","b lymphocyte","b lymphocytes","b-lymphocyte","b cell","b cells","plasma cell","plasma cells"]}'::jsonb,
   null,
   'B lymphocytes recognise an antigen and divide. Their plasma cells release antibodies against that antigen.',
   null,
   '{"phagocyte_named":"Answering phagocyte names the cell that engulfs pathogens, not the one that makes antibodies."}'::jsonb,
   'authored',
   true,
   null),

  -- english / language-devices / Y9 / difficulty 2
  ('65263ae3-a95c-444d-8f4d-695113c23293',
   'retrieval',
   'english',
   'language analysis',
   'language-devices',
   'Y9',
   2,
   'Name the device used in this line: The wind whispered through the trees.',
   '{"type":"exact","value":"personification","alternates":["personified"]}'::jsonb,
   null,
   'Whispering is something a person does. Giving a human action to the wind is personification.',
   null,
   '{"metaphor_default":"Answering metaphor is close, but the line gives a human action to something non-human, which is personification."}'::jsonb,
   'authored',
   true,
   null),

  -- english / language-devices / Y13 / difficulty 7
  ('c25e4c81-a4a4-43eb-8746-0f3f37918791',
   'transfer',
   'english',
   'language analysis',
   'language-devices',
   'Y13',
   7,
   'Name the device used in this advertising line: Our engines wake the city.',
   '{"type":"exact","value":"personification","alternates":["personified"]}'::jsonb,
   null,
   'Waking is something a person does. Giving that action to the engines is personification.',
   null,
   '{"hyperbole_default":"Answering hyperbole reads the line as exaggeration; the line gives a human action to the engines, which is personification."}'::jsonb,
   'authored',
   true,
   '65263ae3-a95c-444d-8f4d-695113c23293'),

  -- english / apostrophes / Y9 / difficulty 3
  ('bb6b1675-c457-40db-8d0c-5fbf21bc7725',
   'retrieval',
   'english',
   'punctuation',
   'apostrophes',
   'Y9',
   3,
   'Which sentence uses the apostrophe correctly?',
   '{"type":"choice","index":1}'::jsonb,
   null,
   'The owners belong to more than one dog, so the apostrophe goes after the plural s. The possessive its never takes an apostrophe.',
   '["The dog wagged it''s tail.","The dogs'' owners waited outside.","The dog''s are barking.","Its'' collar was red."]'::jsonb,
   '{"its_contraction":"Choosing the tail option uses it''s, which is short for it is; the possessive its takes no apostrophe."}'::jsonb,
   'authored',
   true,
   null),

  -- english / spelling-homophones / Y9 / difficulty 2
  ('dac01fdf-550a-4bf1-8045-fb2d2130f06f',
   'practice',
   'english',
   'spelling',
   'spelling-homophones',
   'Y9',
   2,
   'Choose the correct word to fill the gap: The team lost ___ nerve.',
   '{"type":"choice","index":1}'::jsonb,
   null,
   'The nerve belongs to the team, so the possessive their is correct. They''re is short for they are, and there refers to a place.',
   '["they''re","their","there","theirs"]'::jsonb,
   '{"contraction_chosen":"Choosing they''re uses the contraction of they are; the sentence needs the possessive their."}'::jsonb,
   'authored',
   true,
   null),

  -- english / active-passive-voice / Y10 / difficulty 4
  ('856bfce1-e1d1-46d3-8969-6e0fd5158051',
   'reasoning',
   'english',
   'grammar',
   'active-passive-voice',
   'Y10',
   4,
   'Rewrite this sentence in the active voice: The window was broken by the boy.',
   '{"type":"exact","value":"the boy broke the window"}'::jsonb,
   null,
   'The active voice puts the person doing the action first, so the sentence becomes: The boy broke the window.',
   null,
   '{"agent_removed":"Answering that the window broke drops the boy; the active voice keeps him as the subject."}'::jsonb,
   'authored',
   true,
   null),

  -- english / word-class / Y10 / difficulty 3
  ('30e0b0e5-5962-40c3-8ef1-504f68c16bb5',
   'practice',
   'english',
   'grammar',
   'word-class',
   'Y10',
   3,
   'Give the word class of quickly in this sentence: She quickly closed the door.',
   '{"type":"exact","value":"adverb","alternates":["an adverb","adverbs"]}'::jsonb,
   null,
   'Quickly describes how the verb closed was done, so it is an adverb.',
   null,
   '{"adjective_chosen":"Answering adjective describes a word that modifies a noun; quickly modifies the verb closed."}'::jsonb,
   'authored',
   true,
   null),

  -- english / essay-structure-point-evidence / Y10 / difficulty 5
  ('8c20a58c-bcef-4a3a-868a-c6cea55c66dc',
   'reasoning',
   'english',
   'language analysis',
   'essay-structure-point-evidence',
   'Y10',
   5,
   'Write one analytical sentence about the effect of the verb whispered in: The wind whispered through the trees.',
   '{"type":"rubric","passMark":0.6,"criteria":[{"id":"device","weight":1,"keywords":["personification","personifies","verb"]},{"id":"effect","weight":1,"keywords":["gentle","quiet","soft","calm","peaceful","soothing","secretive","intimate"]},{"id":"reader","weight":1,"keywords":["suggests","implies","creates","conveys","makes the reader","gives the impression"]}]}'::jsonb,
   '{"criteria":[{"id":"device","weight":1,"keywords":["personification","personifies","verb"]},{"id":"effect","weight":1,"keywords":["gentle","quiet","soft","calm","peaceful","soothing","secretive","intimate"]},{"id":"reader","weight":1,"keywords":["suggests","implies","creates","conveys","makes the reader","gives the impression"]}],"passMark":0.6}'::jsonb,
   'Name the device, then say what it makes the reader picture or feel. For example: the personification in whispered suggests a gentle, secretive movement rather than a violent one.',
   null,
   '{"feature_spotting":"Naming the device without saying what it makes the reader think or feel stops at feature spotting."}'::jsonb,
   'authored',
   true,
   null),

  -- english / unseen-poetry-analysis / Y11 / difficulty 6
  ('b8e04401-c558-4b33-85e8-df4f76028a11',
   'reasoning',
   'english',
   'poetry',
   'unseen-poetry-analysis',
   'Y11',
   6,
   'A poem ends with a single-word line: Alone. Explain the effect of this structural choice.',
   '{"type":"rubric","passMark":0.6,"criteria":[{"id":"meaning","weight":1,"keywords":["isolation","isolated","loneliness","lonely","separated","cut off","abandoned"]},{"id":"structure","weight":1,"keywords":["single word","one word","short line","final line","last line","white space","pause","stands apart"]},{"id":"reader","weight":1,"keywords":["reader","emphasis","emphasises","lingers","draws attention","stark"]}]}'::jsonb,
   '{"criteria":[{"id":"meaning","weight":1,"keywords":["isolation","isolated","loneliness","lonely","separated","cut off","abandoned"]},{"id":"structure","weight":1,"keywords":["single word","one word","short line","final line","last line","white space","pause","stands apart"]},{"id":"reader","weight":1,"keywords":["reader","emphasis","emphasises","lingers","draws attention","stark"]}],"passMark":0.6}'::jsonb,
   'The line is held apart by white space, so the eye rests on it. The single word acts out the isolation it describes, and because it is the last thing on the page it stays with the reader.',
   null,
   '{"structure_without_effect":"Saying only that the line is short describes the choice without explaining what it does to the reader."}'::jsonb,
   'authored',
   true,
   null),

  -- english / shakespeare-context / Y11 / difficulty 4
  ('ab64c2cd-dd5f-4fb3-89b7-3c2777a12dfd',
   'retrieval',
   'english',
   'drama',
   'shakespeare-context',
   'Y11',
   4,
   'Give the term for a speech in which a character alone on stage speaks their thoughts aloud.',
   '{"type":"exact","value":"soliloquy","alternates":["a soliloquy","soliloquies"]}'::jsonb,
   null,
   'A soliloquy is spoken by a character alone on stage, so the audience hears thoughts the other characters do not.',
   null,
   '{"monologue_named":"Answering monologue names a long speech delivered to others; a soliloquy is spoken alone."}'::jsonb,
   'authored',
   true,
   null),

  -- english / punctuation-semicolon / Y12 / difficulty 5
  ('65cb4a89-1006-451f-8b3a-f27b91c4ea99',
   'reasoning',
   'english',
   'punctuation',
   'punctuation-semicolon',
   'Y12',
   5,
   'Which sentence uses a semicolon correctly?',
   '{"type":"choice","index":1}'::jsonb,
   null,
   'A semicolon joins two complete clauses. The rain stopped and the match went ahead can each stand alone as a sentence; the other options attach a phrase or a conjunction.',
   '["I was late; because the bus broke down.","The rain stopped; the match went ahead.","She packed a bag; and left.","We waited; hoping for news."]'::jsonb,
   '{"clause_and_phrase":"Choosing the waiting option joins a clause to a phrase; a semicolon needs a full clause on each side."}'::jsonb,
   'authored',
   true,
   null),

  -- english / tone-register / Y12 / difficulty 6
  ('f2e5681d-dbb9-46db-88ff-e42f1d90d3ad',
   'reasoning',
   'english',
   'writing',
   'tone-register',
   'Y12',
   6,
   'A letter to a headteacher opens: Hey, so I reckon your rules are rubbish. Which change most improves the register?',
   '{"type":"choice","index":1}'::jsonb,
   null,
   'Register comes from word choice. Replacing hey, reckon and rubbish with formal phrasing fits the audience, while length and punctuation do not change the register.',
   '["Add more exclamation marks","Replace the slang with formal phrasing","Make the sentence longer","Add a rhetorical question"]'::jsonb,
   '{"length_as_formality":"Choosing a longer sentence assumes formality is about length; register comes from word choice."}'::jsonb,
   'authored',
   true,
   null),

  -- english / rhetoric-analysis / Y13 / difficulty 7
  ('8f0d126e-1f9b-4df8-8591-bb6c07250afe',
   'reasoning',
   'english',
   'rhetoric',
   'rhetoric-analysis',
   'Y13',
   7,
   'A speech begins three consecutive sentences with the same clause: We will not stop. Name the device and explain its effect in one or two sentences.',
   '{"type":"rubric","passMark":0.6,"criteria":[{"id":"device","weight":1,"keywords":["anaphora"]},{"id":"effect","weight":1,"keywords":["insistent","momentum","builds","determination","relentless","emphasis","urgency","memorable","drives"]},{"id":"audience","weight":1,"keywords":["audience","listener","listeners","reader","persuade","rally"]}]}'::jsonb,
   '{"criteria":[{"id":"device","weight":1,"keywords":["anaphora"]},{"id":"effect","weight":1,"keywords":["insistent","momentum","builds","determination","relentless","emphasis","urgency","memorable","drives"]},{"id":"audience","weight":1,"keywords":["audience","listener","listeners","reader","persuade","rally"]}],"passMark":0.6}'::jsonb,
   'Repetition at the start of successive clauses is anaphora. The repeated opening builds momentum and drums the promise into the audience, so the speaker sounds unshakeable.',
   null,
   '{"repetition_imprecise":"Calling it repetition is accurate but imprecise; repetition at the start of successive clauses is anaphora."}'::jsonb,
   'authored',
   true,
   null)
on conflict (id) do nothing;
